### ISSUE TITLE
[Security] Introduce another way of providing nexus admin credentials

### ISSUE THREAD

**Issue by ppxl** [cloudogu/nexus-claim#9]
Currently (Nexus 3.23.0-6), the Nexus dogu exports an environment variable that contains an technical admin credential. `nexus-claim` reads this environment variable and uses it. As the environment variable is exported, all new processes are supplied with that environment variable.

It seems that this credential is only exported because of the usage of `nexus-claim`.

This imposed security risk of unwarranted users accessing this variable should be reduced. I propose a flag that take credentials like this:

```bash
nexus-claim plan -p ${unexportedCredential} -i "${PLAN}" -o "-" | nexus-claim apply -p ${unexportedCredential} -i "-"
```

**Comment by Subaro** [comment]
The current implementation already support the -p parameter. This bug also affects multiple nexus tools and should be further solved in the Cloudogu nexus repository. I created a respective issue: see https://github.com/cloudogu/nexus/issues/59
